import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { z } from 'zod';
import { generateTypingPassage } from '@/lib/ai/generate-typing-passage';
import type { Database } from '@/types/database.types';

type AssessmentAttemptInsert = Database['public']['Tables']['assessment_attempts']['Insert'];

const startAttemptSchema = z.object({
  assessment_template_id: z.string().uuid(),
  passage_used: z.string().optional(), // Optional - for when passage is already generated
});

/**
 * POST /api/screening/attempts/start
 * Start a new assessment attempt
 * Can be called with pre-generated passage to avoid regenerating
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    
    // Verify authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Validate request
    const body = await request.json();
    const validationResult = startAttemptSchema.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        { error: 'Validation failed', details: validationResult.error.issues },
        { status: 400 }
      );
    }

    const { assessment_template_id, passage_used } = validationResult.data;

    // Use provided passage or empty string (passage will be generated by prepare endpoint)
    const passage = passage_used || '';

    // Create attempt record
    const attemptData: AssessmentAttemptInsert = {
      user_id: user.id,
      assessment_template_id,
      passage_used: passage,
      status: 'in_progress',
      is_submitted: false,
      started_at: new Date().toISOString(),
    };

    const { data: attempt, error: insertError } = await supabase
      .from('assessment_attempts')
      .insert(attemptData)
      .select()
      .single();

    if (insertError) {
      console.error('Error creating attempt:', insertError);
      return NextResponse.json({ error: 'Failed to start attempt' }, { status: 500 });
    }

    return NextResponse.json({
      attempt_id: attempt.id,
    }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/screening/attempts/start:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

